# GENERATED! Do not edit directly. This file is automatically generated by the deploy script.
class Ctoolbox < Formula
  desc "Collective Toolbox: A graph‑based workspace for linking documents and data"
  homepage "https://collectivetoolbox.com/"
  url "https://collectivetoolbox.com/releases/src/ctoolbox-src-0.1.26-a52574617ff2984fa10d19751959eb95f905f303.tar.gz"
  version "0.1.26"
  sha256 "47ae26cc445b69fa99668c13d25046c0ed11c333b329510f869dc77612c0240d"

  # We use env :userpaths to preserve the host's rustup and musl-tools paths in CI.
  env :userpaths

  depends_on "pkg-config" => :build
  depends_on "rust" => :build
  depends_on "cargo-deny" => :build

  resource "dependencies" do
    url "https://collectivetoolbox.com/releases/src/ctoolbox-dependencies-0.1.26-a52574617ff2984fa10d19751959eb95f905f303.tar.gz"
    sha256 "2e147794454fa51537a558f4780fcf893a403fb4741a6f29f082dd155e5abf03"
  end

  def install
    # bison expat libffi meson ninja
    # Extract vendor.tar inside the vendor/ directory to restore git-archived path dependencies.
    mkdir "-p", "vendor"
    system "tar", "-xf", "vendor.tar", "-C", "vendor"

    # Stage dependencies to vendor/ctb-vendored
    (buildpath/"vendor/ctb-vendored").mkpath
    resource("dependencies").stage(buildpath/"vendor/ctb-vendored")

    # Configure Cargo to run offline and use the vendored sources
    File.open(".cargo/config.toml", "a") do |f|
      f.write <<~EOS

        [source.crates-io]
        replace-with = "vendored-sources"

        [source.vendored-sources]
        directory = "vendor/ctb-vendored/vendor"

        [source."https://github.com/boa-dev/boa.git"]
        git = "https://github.com/boa-dev/boa.git"
        rev = "ffec9244d4267406d66aef8b3c8a1d89730df5b4"
        replace-with = "vendored-sources"

        [source."https://github.com/rust-dark-light/dark-light.git"]
        git = "https://github.com/rust-dark-light/dark-light.git"
        rev = "0f18d2fbcaa5d1c175db8aae7d53428988d7e961"
        replace-with = "vendored-sources"
      EOS
    end

    # rm_f "./vendor/TypeScript-built.tar" # Remove the TypeScript-built tarball to avoid using it in the build

    # Run the offline build using the provided runner script (which sandboxes network access)
    system "./scripts/run-without-network", "./build", "--release", "--no-tests", "--no-docs", "linux-x64"
    system "./build", "--release", "--no-tests", "--no-docs", "linux-x64"

    # Install the binaries
    bin.install "built/linux-x64/ctoolbox"
    bin.install "built/linux-x64/ctoolbox.rsrc"
  end

  test do
    # Simple validation command to verify the installation
    assert_match "Collective Toolbox", shell_output("#{bin}/ctoolbox help")
  end
end
