# GENERATED! Do not edit directly. This file is automatically generated by the deploy script.
class Ctoolbox < Formula
  desc "Collective Toolbox: A graph‑based workspace for linking documents and data"
  homepage "https://collectivetoolbox.com/"
  url "https://collectivetoolbox.com/releases/src/ctoolbox-src-0.1.22-ca730bc38359bfad79a8b042ca8c8aac5b13a743.tar.gz"
  version "0.1.22"
  sha256 "75ea728ccf3ad4e575c013dc0920610e0a4fd319eb2b63ef55b0ad34bcc4ff7c"

  # We use env :userpaths to preserve the host's rustup and musl-tools paths in CI.
  env :userpaths

  # depends_on "bison" => :build
  # depends_on "expat" => :build
  # depends_on "libffi" => :build
  # depends_on "meson" => :build
  # depends_on "ninja" => :build
  depends_on "pkg-config" => :build
  depends_on "rust" => :build

  resource "dependencies" do
    url "https://collectivetoolbox.com/releases/src/ctoolbox-dependencies-0.1.22-ca730bc38359bfad79a8b042ca8c8aac5b13a743.tar.gz"
    sha256 "a5a310a4d2189b93bdefd7ae3e3dde9b04975515072081c39571c822401cc76b"
  end

  def install
    # Extract vendor.tar inside the vendor/ directory to restore git-archived path dependencies.
    system "tar", "-xf", "vendor/vendor.tar", "-C", "vendor"

    # Stage dependencies to vendor/ctb-vendored
    (buildpath/"vendor/ctb-vendored").mkpath
    resource("dependencies").stage(buildpath/"vendor/ctb-vendored")

    # Configure Cargo to run offline and use the vendored sources
    File.open(".cargo/config.toml", "a") do |f|
      f.write <<~EOS

        [source.crates-io]
        replace-with = "vendored-sources"

        [source.vendored-sources]
        directory = "vendor/ctb-vendored/vendor"
      EOS
    end

    rm "./vendor/TypeScript-built.tar" # Remove the TypeScript-built tarball to avoid using it in the build

    # Run the offline build using the provided runner script (which sandboxes network access)
    system "./scripts/run-without-network", "./build", "--release", "--no-tests", "--no-docs", "linux-x64"
    system "./build", "--release", "--no-tests", "--no-docs", "linux-x64"

    # Install the binaries
    bin.install "built/linux-x64/ctoolbox"
    bin.install "built/linux-x64/ctoolbox.rsrc"
  end

  test do
    # Simple validation command to verify the installation
    assert_match "Collective Toolbox", shell_output("#{bin}/ctoolbox help")
  end
end
